name: "Test and lint the branch"

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  on-push:
    uses: bactions/workflows/.github/workflows/on-push-go.yml@v2
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
